# Generated by Django 4.2.13 on 2024-05-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('params', models.TextField()),
                ('data', models.JSONField()),
            ],
            options={
                'unique_together': {('endpoint', 'params')},
            },
        ),
    ]
